# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pbarray.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pbarray.proto',
  package='pbarray',
  serialized_pb=_b('\n\rpbarray.proto\x12\x07pbarray\"\x15\n\x04Head\x12\r\n\x05items\x18\x01 \x03(\x05\"(\n\x04Meta\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.pbarray.MetaItem\"g\n\x08MetaItem\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05label\x18\x04 \x01(\x05\x12\x1b\n\x05\x62oxes\x18\x05 \x03(\x0b\x32\x0c.pbarray.Box\"\x18\n\x08\x44\x61taItem\x12\x0c\n\x04jpeg\x18\x01 \x01(\x0c\"T\n\x03\x42ox\x12\x0f\n\x07start_x\x18\x01 \x01(\x05\x12\x0f\n\x07start_y\x18\x02 \x01(\x05\x12\r\n\x05\x65nd_x\x18\x03 \x01(\x05\x12\r\n\x05\x65nd_y\x18\x04 \x01(\x05\x12\r\n\x05label\x18\x05 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HEAD = _descriptor.Descriptor(
  name='Head',
  full_name='pbarray.Head',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='pbarray.Head.items', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=47,
)


_META = _descriptor.Descriptor(
  name='Meta',
  full_name='pbarray.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='pbarray.Meta.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=89,
)


_METAITEM = _descriptor.Descriptor(
  name='MetaItem',
  full_name='pbarray.MetaItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='pbarray.MetaItem.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='pbarray.MetaItem.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='pbarray.MetaItem.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='pbarray.MetaItem.label', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boxes', full_name='pbarray.MetaItem.boxes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=194,
)


_DATAITEM = _descriptor.Descriptor(
  name='DataItem',
  full_name='pbarray.DataItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jpeg', full_name='pbarray.DataItem.jpeg', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=220,
)


_BOX = _descriptor.Descriptor(
  name='Box',
  full_name='pbarray.Box',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_x', full_name='pbarray.Box.start_x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_y', full_name='pbarray.Box.start_y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_x', full_name='pbarray.Box.end_x', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_y', full_name='pbarray.Box.end_y', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='pbarray.Box.label', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=306,
)

_META.fields_by_name['items'].message_type = _METAITEM
_METAITEM.fields_by_name['boxes'].message_type = _BOX
DESCRIPTOR.message_types_by_name['Head'] = _HEAD
DESCRIPTOR.message_types_by_name['Meta'] = _META
DESCRIPTOR.message_types_by_name['MetaItem'] = _METAITEM
DESCRIPTOR.message_types_by_name['DataItem'] = _DATAITEM
DESCRIPTOR.message_types_by_name['Box'] = _BOX

Head = _reflection.GeneratedProtocolMessageType('Head', (_message.Message,), dict(
  DESCRIPTOR = _HEAD,
  __module__ = 'pbarray_pb2'
  # @@protoc_insertion_point(class_scope:pbarray.Head)
  ))
_sym_db.RegisterMessage(Head)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'pbarray_pb2'
  # @@protoc_insertion_point(class_scope:pbarray.Meta)
  ))
_sym_db.RegisterMessage(Meta)

MetaItem = _reflection.GeneratedProtocolMessageType('MetaItem', (_message.Message,), dict(
  DESCRIPTOR = _METAITEM,
  __module__ = 'pbarray_pb2'
  # @@protoc_insertion_point(class_scope:pbarray.MetaItem)
  ))
_sym_db.RegisterMessage(MetaItem)

DataItem = _reflection.GeneratedProtocolMessageType('DataItem', (_message.Message,), dict(
  DESCRIPTOR = _DATAITEM,
  __module__ = 'pbarray_pb2'
  # @@protoc_insertion_point(class_scope:pbarray.DataItem)
  ))
_sym_db.RegisterMessage(DataItem)

Box = _reflection.GeneratedProtocolMessageType('Box', (_message.Message,), dict(
  DESCRIPTOR = _BOX,
  __module__ = 'pbarray_pb2'
  # @@protoc_insertion_point(class_scope:pbarray.Box)
  ))
_sym_db.RegisterMessage(Box)


# @@protoc_insertion_point(module_scope)
